FROM golang:1.23 AS build

ENV CGO_ENABLED=0
WORKDIR /src
COPY go.mod go.sum ./
COPY balancer ./balancer

RUN cd /src && go build -o /balancer ./balancer/main.go

FROM alpine:3.20

COPY --from=build /balancer /balancer

ENTRYPOINT [ "/balancer" ]